theme: jekyll-theme-hacker
title: "Ditio: Trustworthy Auditing of Sensor Activities in Mobile & IoT Devices"
name: "Ditio: Trustworthy Auditing of Sensor Activities in Mobile & IoT Devices"
show_downloads: true
